<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>brbkasm</string>
   </array>
  <key>name</key>
  <string>BrubeckAssembly</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.BrubeckAssembly</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b((add)|(sub)|(mul)|(div)|(mod)|(inc)|(dec)|(shift)|(rotate)|(and)|(or)|(xor)|(not)|(clearflags))\b)</string>
          <key>name</key>
          <string>keyword.operator.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b((label)|(subr)|(return)|(call)|(cmp)|(jeq)|(jneq)|(jmageq)|(jmagneq)|(jlt)|(jgt)|(jlteq)|(jgteq)|(jz)|(jnz)|(ju))\b)</string>
          <key>name</key>
          <string>keyword.control.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(%\d(?![^\x{002c}\s]))</string>
          <key>name</key>
          <string>variable.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(%[AEIOUaeiou]{10}(?![^\x{002c}\s]))</string>
          <key>name</key>
          <string>variable.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^\x{002c}\s])[AEIOUaeiou]{3}(?![^\x{002c}\s])</string>
          <key>name</key>
          <string>constant.numeric.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^\x{002c}\s])&apos;.&apos;(?![^\x{002c}\s])</string>
          <key>name</key>
          <string>constant.characters.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b((mov)|(movloc)|(vramadd)|(vramsub)|(dwrite)|(dread)|(dpset)|(dpinc)|(dpdec)|(push)|(pop)|(pushall)|(popall)|(int))\b)</string>
          <key>name</key>
          <string>keyword.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?&lt;=((label)|(subr)|(call)|(jeq)|(jneq)|(jmageq)|(jmagneq)|(jlt)|(jgt)|(jlteq)|(jgteq)|(jz)|(jnz)|(ju)))\s*[^\x{002c}\s]*\b)</string>
          <key>name</key>
          <string>constant.other.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bhalt\b)</string>
          <key>name</key>
          <string>keyword.other.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(;.*)</string>
          <key>name</key>
          <string>comment.BrubeckAssembly</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.BrubeckAssembly</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
